version: '3.8'

services:
  # Service for the PostgreSQL database
  db:
    image: postgres:15-alpine
    container_name: card_process_db
    environment:
      POSTGRES_USER: smartcast
      POSTGRES_PASSWORD: smartcast@postgres
      POSTGRES_DB: card_process
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Service for the Redis server
  redis:
    image: redis:latest
    container_name: card_process_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Service for the Java application
  app:
    build: .
    container_name: card_process_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_process
      SPRING_DATASOURCE_USERNAME: smartcast
      SPRING_DATASOURCE_PASSWORD: smartcast@postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

# Define a shared network for the services
networks:
  app-network:
    driver: bridge

# Define a named volume for PostgreSQL data persistence
volumes:
  db_data:
